parameters:
- name: functionApps
  type: object

stages:

- stage: Build_CopyParameters

  jobs:
  - ${{ each func in parameters.functionApps }}:
      - job: Build_${{ func.name }}
        strategy:
          maxParallel: 2
          matrix:
            debug:
              BuildConfiguration: debug
            release:
              BuildConfiguration: release

        steps:
        
        - task: DownloadBuildArtifacts@0
          inputs:
            artifactName: '$(Build.BuildNumber)_$(BuildConfiguration)'
            downloadPath: Service\GroupMembershipManagement

        - powershell: |
                  $bicepTemplates = Get-ChildItem -Filter "template.bicep" -Recurse
                  foreach($template in $bicepTemplates)
                  {
                    az bicep build --file $template.FullName
                  }
          displayName: 'Compile Bicep templates'

        - task: CopyFiles@2
          displayName: 'copy ${{ func.name }} function arm templates'
          inputs:
            SourceFolder: Service/GroupMembershipManagement/Hosts/${{ func.name }}
            Contents: '**\Infrastructure\**'
            TargetFolder: '$(build.artifactstagingdirectory)/functions_arm_templates/${{ func.name }}'
            OverWrite: true

        - task: PublishBuildArtifacts@1
          displayName: 'publish functions artifacts'
          inputs:
            PathtoPublish: '$(build.artifactstagingdirectory)'
            ArtifactName: '$(Build.BuildNumber)_$(BuildConfiguration)'
