stages:

- stage: Build_CommonInternal
  jobs:
  - job: Build_CommonInternal
    strategy:
      maxParallel: 2
      matrix:
        debug:
          BuildConfiguration: debug
        release:
          BuildConfiguration: release

    steps:

    - task: CopyFiles@2
      displayName: 'Copy arm templates'
      inputs:
        SourceFolder: Infrastructure
        TargetFolder: '$(build.artifactstagingdirectory)/Infrastructure'

    - task: CopyFiles@2
      displayName: 'Copy release management scripts'
      inputs:
        SourceFolder: Scripts
        TargetFolder: '$(build.artifactstagingdirectory)/Scripts'

    - task: PublishBuildArtifacts@1
      displayName: 'Publish artifact'
      inputs:
        PathtoPublish: '$(build.artifactstagingdirectory)'
        ArtifactName: '$(Build.BuildNumber)_$(BuildConfiguration)'